"""add memory tables: dialogue_states + user_profiles + conversations.summary

Revision ID: 618835c30a0e
Revises: a1304eeb2d47
Create Date: 2026-05-19 10:50:04.277353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '618835c30a0e'
down_revision: Union[str, Sequence[str], None] = 'a1304eeb2d47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialogue_states',
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('slots', sa.JSON(), nullable=False, comment='累积的对话状态键值对'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('thread_id')
    )
    op.create_index(op.f('ix_dialogue_states_thread_id'), 'dialogue_states', ['thread_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=False, comment='例如 preferred_brands/budget_range/history_categories'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.add_column('conversations', sa.Column('summary', sa.Text(), nullable=True, comment='老消息 LLM 摘要'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'summary')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_dialogue_states_thread_id'), table_name='dialogue_states')
    op.drop_table('dialogue_states')
    # ### end Alembic commands ###
